FROM {{ image }}

FROM debian:latest as ansible

ENV DEBIAN_FRONTEND="noninteractive" \
    TZ="Europe/Paris"

RUN apt-get update  -qq && \
    apt-get upgrade -qqy

RUN apt-get install -qqy --no-install-recommends \
      build-essential \
      libffi-dev \
      libssl-dev \
      python-dev \
      python-pip \
      python-setuptools \
      python-wheel && \
      apt-get clean

RUN pip install --upgrade \
      ansible \
      cryptography

FROM debian:latest

COPY --from=ansible /usr/local /usr/local

RUN apt-get update  -qq && \
    apt-get upgrade -qqy && \
    apt-get install -qqy \
      python \
      sudo \
      systemd && \
    apt-get clean

WORKDIR /etc/ansible

RUN /bin/echo -e \
      '[local]\nlocalhost ansible_connection=local' > \
      /etc/ansible/hosts

VOLUME [ "/sys/fs/cgroup" ]

HEALTHCHECK NONE








MAINTAINER Rob McQueen

# Install Ansible prerequisites
{% if family == "Debian" %}
RUN apt-get update && apt-get install -y \
  build-essential \
  libffi-dev \
  libyaml-dev \
  libssl-dev \
  python-dev \
  python-virtualenv \
  sudo
{% elif family == "RedHat" %}
RUN yum install -y \
  gcc \
  libffi-devel \
  libyaml-devel \
  openssl-devel \
  epel-release \
  python-pip \
  python-virtualenv \
  sudo
{% elif family == "Gentoo" %}
# do the 'emerge --sync' in base image, not here  -- not polite to
# keep pulling from the rsync servers on every run of a test
RUN emerge \
  dev-python/pyyaml \
  dev-python/pip \
  dev-python/virtualenv \
  app-admin/sudo \
  app-portage/gentoolkit && eselect python set python2.7
{% else %}
RUN echo "OS family {{ family }} not yet supported, try adding it to Dockerfile.j2" ; exit 1
{% endif %}

# Install Ansible
RUN mkdir /opt/ansible && virtualenv /opt/ansible/venv && \
  . /opt/ansible/venv/bin/activate  && \
  pip install --upgrade setuptools && \
  pip install ansible

ADD . /build
COPY .ansible-test /build
WORKDIR /build

CMD . /opt/ansible/venv/bin/activate && ansible-playbook -i inventory.yml \
    -c local -s -e testing=true -e role=$DOCKER_TEST_ROLE \
    {{ extra_args| join(" ") }} playbook.yml; /bin/bash
